# Puerto estándar
listener 1883
# Permitir conexiones sin usuario/contraseña (puedes cambiarlo luego)
allow_anonymous true
# Persistencia
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
