FROM nodered/node-red:latest
USER root
COPY ./data/package.json /data/package.json
RUN chown -R node-red:node-red /data
USER node-red
WORKDIR /data
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production
WORKDIR /usr/src/node-red
